# Don't print a new line at the start of the prompt
add_newline = false
format = """\
    $username\
    $hostname\
    $time\
    $package\
    $golang\
    $java\
    $nodejs\
    $python\
    $terraform\
    $conda\
    $crystal\
    $cmd_duration\
    $jobs\
    $battery\
    $docker_context\
    $kubernetes\
    $aws\
    $line_break\
    $exec_code\
    $cmd_duration\
    $vi_mode\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $character\
"""



[character]      # The name of the module we are configuring is "character"
symbol = "➜ "     # The "symbol" segment is being set to "➜"

[directory]
truncation_length = 8



[kubernetes]
symbol = "☸:"
disabled = false



[docker_context]
disabled = false


[time]
disabled = false
# format = "[ %T ]"


[username]
show_always = true
