name: Jumpbox Docker Build

on: [push]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    services:
      secrets-server:
        image: nginx
        ports:
          - 80:80
        options: -v ${{ github.workspace }}:/usr/share/nginx/html:ro --name secrets-server --hostname secrets-server
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Prepare Secrets
        run: |
          echo "${{ secrets.SECRETS_SH }}" >> $GITHUB_WORKSPACE/config/secrets.sh
      - name: Build Docker Image
        run: |
          DOCKER_BUILD_NETWORK=$(docker network ls -f label=e87b52 --format "{{.Name}}" | head -1)  
          echo dbn=$DOCKER_BUILD_NETWORK
          docker run --network $DOCKER_BUILD_NETWORK --rm -t  ubuntu curl -- http://secrets-server/Dockerfile
          docker build --network $DOCKER_BUILD_NETWORK -t yogendra/pcf-tools:latest .
      - name: Test Docker Image
        run: |
          echo WIP
      - name: Docker Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          login-server: docker.io
      - name: Push Docker Image
        run: |
          docker push yogendra/pcf-tools:latest
