name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: |
        docker build -t yogendra/pcf-tools:latest .
    - name: Test Docker Image
      run: |
        echo WIP
    - name: Push Docker Image
      run: |
        docker push yogendra/pcf-tools:latest
